{:foreign-libs
 [{:file "org/knotation/editor/modes/ntriples.js"
   :file-min "org/knotation/editor/modes/ntriples.min.js"
   :provides [org.knotation.editor.modes.ntriples]}
  {:file "org/knotation/editor/modes/sparql.js"
   :file-min "org/knotation/editor/modes/sparql.min.js"
   :provides [org.knotation.editor.modes.sparql]}
  {:file "org/knotation/editor/modes/turtle.js"
   :file-min "org/knotation/editor/modes/turtle.min.js"
   :provides [org.knotation.editor.modes.turtle]}
  {:file "org/knotation/editor/modes/javascript.js"
   :file-min "org/knotation/editor/modes/javascript.min.js"
   :provides [org.knotation.editor.modes.javascript]}
  {:file "org/knotation/editor/modes/dot.js"
   :file-min "org/knotation/editor/modes/dot.min.js"
   :provides [org.knotation.editor.modes.dot]}
  {:file "org/knotation/editor/addons/hint.js"
   :file-min "org/knotation/editor/addons/hint.min.js"
   :provides [org.knotation.editor.addons.hint]}]}
